language: java
jdk: oraclejdk8

stages:
  - Compile backend
  - Backend test

services:
  - mysql

before_install:
  - cd backend/
  - chmod 777 mvnw
  - mysql -u root --password="" < sql/db.sql

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - script: mvn test -B
