language: java
jdk: oraclejdk8

stages:
  - Compile backend

before_install:
  - cd backend/
  - chmod 777 mvn
  - mysql -e 'CREATE DATABASE dog_training_database;'

services:
  - mysql

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

