language: java
jdk: oraclejdk8

stages:
  - Compile backend
  - Backend test

before_install:
  - cd backend/
  - chmod 777 mvnw
  - mysql -e 'CREATE DATABASE dog_training_database;'
  - mysql -e 'CREATE TABLE dog_training_database.trainer (
      id int NOT NULL AUTO_INCREMENT,
      name varchar(45) DEFAULT NULL,
      email varchar(45) DEFAULT NULL,
      address varchar(45) DEFAULT NULL,
      phone_number int DEFAULT NULL,
      birth_date timestamp(0) NULL DEFAULT NULL,
      birth_place varchar(45) DEFAULT NULL,
      PRIMARY KEY (id)
    ) ;'
    - mysql -e 'INSERT INTO dog_training_database.trainer (name, email, address, phone_number, birth_date, birth_place) 
        VALUES ('Nagy Emma', 'emma1@gmail.com', 'emma_address', 305552145, '1995-03-04T23:00:00.000+0000', 'Budapest'); 
        INSERT INTO dog_training_database.trainer (name, email, address, phone_number, birth_date, birth_place) 
        VALUES ('Kis Károly', 'karcsi25@gmail.com', 'karesz_address', 305552145, '1990-04-15T22:00:00.000+0000', 'Budapest');'

services:
  - mysql

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - script: mvn test -B

deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"
