language: java
jdk: oraclejdk8

stages:
  - Compile backend
  - Backend test

before_install:
  - cd backend/
  - chmod 777 mvnw
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('User1234') where User='user'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE dog_training_database;'

services:
  - mysql

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - script: mvn test -B

deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"
