language: java
jdk: oraclejdk8

stages:
  - Compile backend
  - Backend test

install:

  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - npm install

jobs:
  - include:
    - script: mvn test -B