language: java
jdk: oraclejdk8

stages:
  - Compile backend
  - Backend test

before_install:
  - cd backend/
  - chmod 777 mvnw
  - mysql -e 'CREATE DATABASE dog_training_database;'
  - mysql -e 'ALTER SEQUENCE trainer_seq RESTART WITH 1;'
  - mysql -e 'CREATE TABLE trainer (
      id int NOT NULL DEFAULT NEXTVAL ('trainer_seq'),
      name varchar(45) DEFAULT NULL,
      email varchar(45) DEFAULT NULL,
      address varchar(45) DEFAULT NULL,
      phone_number int DEFAULT NULL,
      birth_date timestamp(0) NULL DEFAULT NULL,
      birth_place varchar(45) DEFAULT NULL,
      PRIMARY KEY (id)
    ) ;'

services:
  - mysql

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - script: mvn test -B

deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"
